---
name: Sort-DataTypes
version: 2.04
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: Sort a list of data using methods relevant to the type of data
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Manip: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Sort::DataTypes:
    file: lib/Sort/DataTypes.pm
    version: 2.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
