perl -I../lib alphabetic.t 1
perl -I../lib alphabetic_hash.t 1
perl -I../lib alphabetic_rev.t 1
perl -I../lib alphabetic_rev_hash.t 1
perl -I../lib date.t 1
perl -I../lib date_hash.t 1
perl -I../lib date_rev.t 1
perl -I../lib date_rev_hash.t 1
perl -I../lib domain.t 1
perl -I../lib domain_hash.t 1
perl -I../lib domain_rev.t 1
perl -I../lib domain_rev_hash.t 1
perl -I../lib function.t 1
perl -I../lib ip.t 1
perl -I../lib ip_hash.t 1
perl -I../lib ip_rev.t 1
perl -I../lib ip_rev_hash.t 1
perl -I../lib length.t 1
perl -I../lib length_hash.t 1
perl -I../lib length_rev.t 1
perl -I../lib length_rev_hash.t 1
perl -I../lib line.t 1
perl -I../lib line_hash.t 1
perl -I../lib line_rev.t 1
perl -I../lib line_rev_hash.t 1
perl -I../lib numdomain.t 1
perl -I../lib numdomain_hash.t 1
perl -I../lib numdomain_rev.t 1
perl -I../lib numdomain_rev_hash.t 1
perl -I../lib numerical.t 1
perl -I../lib numerical_hash.t 1
perl -I../lib numerical_rev.t 1
perl -I../lib numerical_rev_hash.t 1
perl -I../lib numline.t 1
perl -I../lib numline_hash.t 1
perl -I../lib numline_rev.t 1
perl -I../lib numline_rev_hash.t 1
perl -I../lib numpath.t 1
perl -I../lib numpath_hash.t 1
perl -I../lib numpath_rev.t 1
perl -I../lib numpath_rev_hash.t 1
perl -I../lib path.t 1
perl -I../lib path_hash.t 1
perl -I../lib path_rev.t 1
perl -I../lib path_rev_hash.t 1
perl -I../lib sort.t 1
perl -I../lib valid_method.t 1
perl -I../lib version.t 1
perl -I../lib version_hash.t 1
perl -I../lib version_rev.t 1
perl -I../lib version_rev_hash.t 1
